server:
  port: 9092
mybatis:
  mapperLocations: classpath*:com/lijialiang/mapper/*.xml
  type-aliases-package: com.lijialiang.bean
spring:
  rabbitmq:
    username: admin
    password: admin
    addresses: 127.0.0.1:5672
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/ljl-test?useUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true
    username: root
  #解决升级 Spring Boot 2.6后，因循环引用导致启动时报错的问题
  main:
    allow-circular-references: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  redis:
    database: 1
    host: 127.0.0.1
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 2
    port: 6379
